version: '3.9'

services:

  mongodb:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
